### ISSUE TITLE
[Enhancement] geoloc attribute support

### ISSUE THREAD

**Issue by sid6mathur** [massimocandela/geofeed-finder#14]
It would be nice if IP ranges annotated in RIR records with a `geoloc` attribute could be written out in a seperate 'results-geoloc.csv" file. 

While this is out of scope for [RFC9092](https://datatracker.ietf.org/doc/draft-ietf-opsawg-finding-geofeeds/), it's useful for maintainers of IP geolocation datasets. Thanks!

Example: 
https://apps.db.ripe.net/db-web-ui/query?searchtext=%2045.11.228.0%2F24

![image](https://user-images.githubusercontent.com/5669765/162790588-371037fe-5d2e-4bc7-93b1-cd8dc8694b8d.png)

**Comment by massimocandela** [comment]
Hi @s8mathur, as you mentioned, this is out of scope for this tool. If you implement something like that, please, share it open for people to use it.
