### ISSUE TITLE
Minor regression: v1.6.2 accepts junk after IP/prefix in the first column of a feed.

### ISSUE THREAD

**Issue by sgteq** [massimocandela/geofeed-finder#23]
A minor impact issue with 1 feed out of 370. 

v1.5.2 rejects the feed in which values are tab separated causing each line to be a single column 

```
sgteq@desk:~/geofeed$ ./geofeed-finder-linux-x64-1.5.2 -t 94.228.208.0
inetnum: 94.228.208.0/20 https://as47869.net/geofeed.csv [cache]
Error: ,,,, Not valid IP/prefix
```

while v1.6.2 accepts it 

```
serge@desk:~/geofeed$ ./geofeed-finder-linux-x64-1.6.2 -t 94.228.208.0
inetnum: 94.228.208.0/20 https://as47869.net/geofeed.csv [cache]
94.228.208.0/20	NL	NL-NH	Amsterdam	1098 XG,,,,
```

Expected result: v1.6.2 report 'Not valid IP/prefix' error like v1.5.2. Whitespace characters around IP/prefix could be accepted but not any other characters.

**Comment by massimocandela** [comment]
Hi @sgteq,

Nice catch. This is fixed in v1.6.3. Is the increasing amount of garbage a sign that RFC9092 is taking off? :)
