### ISSUE TITLE
Clarify -u and -r in documentation

### ISSUE THREAD

**Issue by sid6mathur** [massimocandela/geofeed-finder#31]
As a tool user, I would like the output CSV to contain invalid ISO codes (RFC 8805) as I wish to post-process them. It's not clear from the README how -u and -r differ. Can the explanation be improved? 

```
-k | Keep entries with invalid ISO codes. Not recommended.
-u | Keep invalid subdivisions (accept invalid ISO regions/subdivisions, but keep validating the rest). Not recommended.
-r | Remove invalid subdivisions but keep the rest of the geofeed if valid.
```

Does -u=true imply -r=false , for example?

**Comment by massimocandela** [comment]
with -k:
```
1.2.3.4,UK,UK-ENG,  >  1.2.3.4,UK,UK-ENG,
1.2.3.4,GB,UK-ENG,  >  1.2.3.4,GB,UK-ENG,
```

with -u:
```
1.2.3.4,UK,UK-ENG,  >  null
1.2.3.4,GB,UK-ENG,  >  1.2.3.4,GB,UK-ENG,
```

with -r:
```
1.2.3.4,UK,UK-ENG,  >  null
1.2.3.4,GB,UK-ENG,  >  1.2.3.4,GB,,
```

**Comment by sid6mathur** [comment]
Thank you! It would be great to add the above example behaviour to the README.

**Comment by sid6mathur** [comment]
As of v1.21.1, entries with 3-letter country codes get suppressed from the output CSV despite the '-k' flag. Can we please let them through? 

Examples from the error log: 
```
2024-01-10T07:54:30+00:00 45.120.137.0/24,USA,US-NC,Asheville, Not valid Country Code (iso-3166-1)
2024-01-10T07:54:30+00:00 45.120.138.0/24,USA,US-NC,Asheville, Not valid Country Code (iso-3166-1)
2024-01-10T07:54:30+00:00 2001:0df2:1001:0000:0000:0000:0000:0000/48,USA,US-NC,Asheville, Not valid Country Code (iso-3166-1)
```

**Comment by massimocandela** [comment]
The logs shows the error no matter what, but it doesn't mean that they are discarded. The specific prefixes are discarded because not linked by any encompassing inetnum for what I can see.

**Comment by sid6mathur** [comment]
> The logs shows the error no matter what, but it doesn't mean that they are discarded. The specific prefixes are discarded because not linked by any encompassing inetnum for what I can see.

Sounds good in that case, thanks for checking :)
