### ISSUE TITLE
Not pulling geofeed information from ARIN ipv6 suballocation

### ISSUE THREAD

**Issue by stevejbauer** [massimocandela/geofeed-finder#38]
using geofeed-finder compiled version 1.13.3 on windows
The initial allocation in arin is: 2607:f558::/32
The sub allocation with the geofeed is 2607:f558:1000::/40

Geofeed-finder is not finding the geofeed in the reassignment.  Should it be following those re-assignments?

**Comment by massimocandela** [comment]
This has been fixed. Thanks for reporting.
