### ISSUE TITLE
Missing module 

### ISSUE THREAD

**Issue by joaoceron** [massimocandela/geofeed-finder#5]
Compiling on Linux, using the build.sh rises an error. 

   pkg/prelude/bootstrap.js:1430
         throw error;
        ^ 

Error: Cannot find module './ConnectorLACNICrir'
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/snapshot/geofeed-finder/node_modules/bulk-whois-parser/dist/connectors/connectorLACNIC.js',
    '/snapshot/geofeed-finder/node_modules/bulk-whois-parser/dist/index.js',
    '/snapshot/geofeed-finder/dist/finder.js',
    '/snapshot/geofeed-finder/dist/index.js'
  ],
  pkg: true
}

**Comment by massimocandela** [comment]
Thank you for reporting. It has been fixed.
